/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { Merged, useGLTF } from "@react-three/drei";
import React, { createContext, useContext, useMemo } from "react";
import { MODELS } from "../../config/azure-gltf";

const context = createContext();
export function Instances({ children, ...props }) {
  const { nodes } = useGLTF(MODELS.TRUCK);
  const instances = useMemo(
    () => ({
      Abody: nodes.A_body,
      Abody1: nodes.A_body0,
      Achrome: nodes.A_chrome52,
      Achrome1: nodes.A_chrome58,
      Achrome2: nodes.A_chrome14,
      Achrome3: nodes.A_chrome39,
      Achrome4: nodes.A_chrome40,
      Achrome5: nodes.A_chrome41,
      Achrome6: nodes.A_chrome42,
      Achrome7: nodes.A_chrome44,
      Agum: nodes.A_gum46,
      Achrome8: nodes.A_chrome34,
      Achrome9: nodes.A_chrome43,
      Asilver: nodes.A_silver14,
      Chrome: nodes.chrome69,
      Chrome1: nodes.chrome70,
      Chrome2: nodes.chrome71,
      Chrome3: nodes.chrome72,
      Chrome4: nodes.chrome73,
      Chrome5: nodes.chrome74,
      Chrome6: nodes.chrome75,
      Glass: nodes.glass3,
      Glass1: nodes.glass4,
      Achrome10: nodes.A_chrome104,
      Achrome11: nodes.A_chrome105,
      Agum1: nodes.A_gum73,
      Asilver1: nodes.A_silver25,
      Gum: nodes.gum74,
      Gum1: nodes.gum75,
      Gum2: nodes.gum76,
      Chrome7: nodes.chrome102,
      Chrome8: nodes.chrome103,
      Gum3: nodes.gum69,
      Gum4: nodes.gum70,
      Gum5: nodes.gum71,
      Gum6: nodes.gum72,
      Silver: nodes.silver24,
      Chrome9: nodes.chrome101,
      Chrome10: nodes.chrome98,
      Gum7: nodes.gum65,
      Gum8: nodes.gum68,
      Gum9: nodes.gum61,
      Chrome11: nodes.chrome97,
      Gum10: nodes.gum64,
      Gum11: nodes.gum24,
      Gum12: nodes.gum26,
      Silver1: nodes.silver17,
      Achrome12: nodes.A_chrome76,
      Achrome13: nodes.A_chrome77,
      Achrome14: nodes.A_chrome78,
      Achrome15: nodes.A_chrome79,
      Achrome16: nodes.A_chrome80,
      Achrome17: nodes.A_chrome81,
      Achrome18: nodes.A_chrome82,
      Agold: nodes.A_gold0,
      Agold1: nodes.A_gold2,
      Aorange: nodes.A_orange3,
      Chrome12: nodes.chrome83,
      Chrome13: nodes.chrome84,
      Gum13: nodes.gum50,
      Gum14: nodes.gum51,
      Silver2: nodes.silver22,
      Silver3: nodes.silver23,
      Achrome19: nodes.A_chrome46,
      Agold2: nodes.A_gold,
      Achrome20: nodes.A_chrome02,
      Achrome21: nodes.A_chrome03,
      Aorange1: nodes.A_orange01,
      Chrome14: nodes.chrome100,
      Chrome15: nodes.chrome99,
      Gum15: nodes.gum66,
      Gum16: nodes.gum67,
      Chrome16: nodes.chrome96,
      Gum17: nodes.gum63,
      Chrome17: nodes.chrome24,
      Gum18: nodes.gum27,
      Gum19: nodes.gum28,
      Silver4: nodes.silver18,
      Silver5: nodes.silver19,
      Achrome22: nodes.A_chrome22,
      Agum2: nodes.A_gum48,
      Achrome23: nodes.A_chrome38,
      Mesh: nodes.Mesh062,
      Mesh1: nodes.Mesh062_1,
      Orange: nodes.orange2,
      Ablackm: nodes.A_black_m2,
      Ablackm1: nodes.A_black_m3,
      Achassis: nodes.A_chassis,
      Achrome24: nodes.A_chrome15,
      Achrome25: nodes.A_chrome16,
      Achrome26: nodes.A_chrome20,
      Mesh2: nodes.Mesh005,
      Mesh3: nodes.Mesh005_1,
      Mesh4: nodes.Mesh006,
      Mesh5: nodes.Mesh006_1,
      Achrome27: nodes.A_chrome26,
      Mesh6: nodes.Mesh015,
      Mesh7: nodes.Mesh015_1,
      Achrome28: nodes.A_chrome29,
      Mesh8: nodes.Mesh020,
      Mesh9: nodes.Mesh020_1,
      Achrome29: nodes.A_chrome35,
      Achrome30: nodes.A_chrome47,
      Achrome31: nodes.A_chrome48,
      Achrome32: nodes.A_chrome49,
      Achrome33: nodes.A_chrome54,
      Achrome34: nodes.A_chrome55,
      Achrome35: nodes.A_chrome56,
      Achrome36: nodes.A_chrome59,
      Achrome37: nodes.A_chrome60,
      Achrome38: nodes.A_chrome61,
      Achrome39: nodes.A_chrome62,
      Mesh10: nodes.Mesh034,
      Mesh11: nodes.Mesh034_1,
      Aglass: nodes.A_glass,
      Agum3: nodes.A_gum29,
      Agum4: nodes.A_gum30,
      Agum5: nodes.A_gum31,
      Agum6: nodes.A_gum32,
      Agum7: nodes.A_gum33,
      Agum8: nodes.A_gum34,
      Agum9: nodes.A_gum36,
      Agum10: nodes.A_gum37,
      Agum11: nodes.A_gum47,
      AObject: nodes.A_Object001,
      Mesh12: nodes.Mesh046,
      Mesh13: nodes.Mesh046_1,
      Mesh14: nodes.Mesh047,
      Mesh15: nodes.Mesh047_1,
      Aredl: nodes.A_red_l1,
      Asilver2: nodes.A_silver20,
      Asilver3: nodes.A_silver21,
      Orange1: nodes.orange1,
      Text: nodes.Text,
      Solid: nodes.Solid1_1,
      Solid1: nodes.Solid1_2,
      Solid2: nodes.Solid1_3,
      Solid3: nodes.Solid1_4,
      Solid4: nodes.Solid1_5,
      Solid5: nodes.Solid1_6,
      Solid6: nodes.Solid1_7,
      Solid7: nodes.Solid1_8,
      Solid8: nodes.Solid1_9,
      Solid9: nodes.Solid1_10,
      Solid10: nodes.Solid1_11,
      Solid11: nodes.Solid1_12,
      Solid12: nodes.Solid1_13,
      Solid13: nodes.Solid1_14,
      Solid14: nodes.Solid1_15,
      Solid15: nodes.Solid1_16,
      Solid16: nodes.Solid1_17,
      Solid17: nodes.Solid1_18,
      Solid18: nodes.Solid1_19,
      Solid19: nodes.Solid1_20,
      Solid20: nodes.Solid1_21,
      Solid21: nodes.Solid1_22,
      Solid22: nodes.Solid1_23,
      Solid23: nodes.Solid1_24,
      Solid24: nodes.Solid1_25,
      Solid25: nodes.Solid1_26,
      Solid26: nodes.Solid1_27,
      Solid27: nodes.Solid1_28,
      Solid28: nodes.Solid1_29,
      Solid29: nodes.Solid1_30,
      Solid30: nodes.Solid1_31,
      Solid31: nodes.Solid1_32,
      Solid32: nodes.Solid1_33,
      Solid33: nodes.Solid1_34,
      Solid34: nodes.Solid1_35,
      Solid35: nodes.Solid1_36,
      Solid36: nodes.Solid1_37,
      Solid37: nodes.Solid1_38,
      Solid38: nodes.Solid1_39,
      Solid39: nodes.Solid1_40,
      Solid40: nodes.Solid1_41,
      Solid41: nodes.Solid1_42,
      Solid42: nodes.Solid1_43,
      Solid43: nodes.Solid1_44,
      Solid44: nodes.Solid1_45,
      Solid45: nodes.Solid1_46,
      Solid46: nodes.Solid1_47,
      Solid47: nodes.Solid1_48,
      Solid48: nodes.Solid1_49,
      Solid49: nodes.Solid1_50,
      Solid50: nodes.Solid1_51,
      Solid51: nodes.Solid1_52,
      Solid52: nodes.Solid1_53,
      Solid53: nodes.Solid1_54,
      Srf: nodes.Srf1,
      Srf1: nodes.Srf2,
      Srf2: nodes.Srf3,
      Srf3: nodes.Srf4,
      Srf4: nodes.Srf5,
      Srf5: nodes.Srf6,
      Srf6: nodes.Srf7,
      Srf7: nodes.Srf8,
      Srf8: nodes.Srf9,
      Text1: nodes.Text002,
      Text2: nodes.Text004,
    }),
    [nodes]
  );
  return (
    <Merged meshes={instances} {...props}>
      {(instances) => (
        <context.Provider value={instances} children={children} />
      )}
    </Merged>
  );
}

export function Model(props) {
  const instances = useContext(context);
  return (
    <group {...props} dispose={null}>
      <group
        position={[0.03, 0.59, -8.48]}
        rotation={[0, -1.57, 0]}
        scale={0.01}
      >
        <group position={[-152.79, -2.91, -2.36]}>
          <instances.Abody position={[-185.62, -56.93, -119.48]} scale={0.01} />
          <instances.Abody1 position={[-22.96, -13.73, -119.48]} scale={0.01} />
          <instances.Achrome
            position={[-22.96, -13.73, -119.48]}
            scale={0.01}
          />
          <instances.Achrome1 position={[186.75, 41.63, 143.07]} scale={0.01} />
        </group>
        <group position={[-463.04, -91.28, 0.48]}>
          <group position={[4.01, 0, 0]}>
            <group position={[2.59, 26.1, 0.11]}>
              <instances.Achrome2
                position={[129.15, -73.45, -0.3]}
                scale={0.01}
              />
              <instances.Achrome3
                position={[118.03, 5.35, -122.43]}
                scale={0.01}
              />
              <instances.Achrome4
                position={[-10.06, -69.27, 30.54]}
                scale={0.01}
              />
              <instances.Achrome5
                position={[-13.68, -11.78, -33.53]}
                scale={0.01}
              />
              <instances.Achrome6
                position={[-13.16, -67.33, 44.44]}
                scale={0.01}
              />
              <instances.Achrome7
                position={[-0.78, 56.73, 47.47]}
                scale={0.01}
              />
              <instances.Agum position={[118.03, 5.35, -122.43]} scale={0.01} />
            </group>
            <instances.Achrome8
              position={[-6.49, -98.87, -80.87]}
              scale={0.01}
            />
            <instances.Achrome9
              position={[-6.73, -48.15, 61.33]}
              scale={0.01}
            />
          </group>
          <instances.Asilver position={[-18.37, -68.14, 49.08]} scale={0.01} />
        </group>
        <group position={[-459.03, -105.63, -95.93]}>
          <instances.Chrome position={[9.48, -17.54, -22.59]} scale={0.01} />
          <instances.Chrome1 position={[-2.89, 7.05, -9.18]} scale={0.01} />
          <instances.Chrome2
            position={[0.85, 9.07, -0.02]}
            rotation={[0, 0, -0.16]}
            scale={0.01}
          />
          <instances.Chrome3 position={[-2.91, -21.22, -4.53]} scale={0.01} />
          <instances.Chrome4 position={[30.12, -20.68, -4.48]} scale={0.01} />
          <instances.Chrome5 position={[3.19, 6.44, 0.19]} scale={0.01} />
          <instances.Chrome6 position={[9.48, -17.54, -2.94]} scale={0.01} />
          <instances.Glass position={[-6.29, -16.4, -21.98]} scale={0.01} />
          <instances.Glass1 position={[-6.28, -16.4, -2.33]} scale={0.01} />
        </group>
        <group position={[-459.03, -105.63, 95.53]}>
          <instances.Chrome position={[9.48, -17.54, -22.59]} scale={0.01} />
          <instances.Chrome1 position={[-2.89, 7.05, -9.18]} scale={0.01} />
          <instances.Chrome2
            position={[0.85, 9.07, -0.02]}
            rotation={[0, 0, -0.16]}
            scale={0.01}
          />
          <instances.Chrome3 position={[-2.91, -21.22, -4.53]} scale={0.01} />
          <instances.Chrome4 position={[30.12, -20.68, -4.48]} scale={0.01} />
          <instances.Chrome5 position={[3.19, 6.44, 0.19]} scale={0.01} />
          <instances.Chrome6 position={[9.48, -17.54, -2.94]} scale={0.01} />
          <instances.Glass position={[-6.29, -16.4, -21.98]} scale={0.01} />
          <instances.Glass1 position={[-6.29, -16.4, -2.33]} scale={0.01} />
        </group>
        <group position={[-384.19, -155.52, -114.49]}>
          <instances.Achrome10 position={[0, 27, -18.33]} scale={0.01} />
          <instances.Achrome11 position={[-0.1, -0.12, -7.27]} scale={0.01} />
          <instances.Agum1 position={[0, 50.75, -15.97]} scale={0.01} />
          <instances.Asilver1 position={[25.08, -6.55, -3.06]} scale={0.01} />
          <instances.Gum position={[0.04, -0.01, -5.27]} scale={0.01} />
          <instances.Gum1 position={[22.2, -3.63, -7.45]} scale={0.01} />
          <instances.Gum2 position={[0.01, 0.04, -17.24]} scale={0.01} />
        </group>
        <group position={[-384.19, -155.52, 115.83]}>
          <instances.Chrome7 position={[0, 27, 18.33]} scale={0.01} />
          <instances.Chrome8 position={[-0.1, -0.12, 7.27]} scale={0.01} />
          <instances.Gum3 position={[0.04, -0.01, 5.27]} scale={0.01} />
          <instances.Gum4 position={[0, 50.75, 15.97]} scale={0.01} />
          <instances.Gum5 position={[0.01, 0.04, 17.24]} scale={0.01} />
          <instances.Gum6 position={[22.2, -3.63, 7.45]} scale={0.01} />
          <instances.Silver position={[25.08, -6.55, 3.06]} scale={0.01} />
        </group>
        <group position={[290.58, -155.52, 102.35]}>
          <instances.Chrome9 position={[0, 24.9, 19.49]} scale={0.01} />
          <instances.Chrome10 position={[0, 23.91, 1.51]} scale={0.01} />
          <instances.Gum7 position={[0.01, 0.05, 5.96]} scale={0.01} />
          <instances.Gum8 position={[0, 50.75, -1.49]} scale={0.01} />
        </group>
        <group position={[414.97, -155.52, 102.35]}>
          <instances.Chrome10 position={[0, 23.91, 1.51]} scale={0.01} />
          <instances.Gum9 position={[0.01, 0.05, 5.96]} scale={0.01} />
          <instances.Chrome11 position={[0, 24.9, 19.49]} scale={0.01} />
          <instances.Gum10 position={[0, 50.75, -1.49]} scale={0.01} />
        </group>
        <group position={[150.08, -155.5, 0.43]}>
          <instances.Gum11 position={[-15.8, -10.6, 122.45]} scale={0.01} />
          <instances.Gum12 position={[-15.8, -10.6, -122.45]} scale={0.01} />
          <instances.Silver1 position={[1.54, 7.29, -66.48]} scale={0.01} />
        </group>
        <group position={[-277.88, -55.9, 0.36]}>
          <instances.Achrome12 position={[0.94, 12.49, 119.83]} scale={0.01} />
          <instances.Achrome13 position={[-17.94, 14.89, 92.07]} scale={0.01} />
          <instances.Achrome14 position={[3.27, -11.71, 97.56]} scale={0.01} />
          <instances.Achrome15 position={[0.94, -15.6, -119.83]} scale={0.01} />
          <instances.Achrome16
            position={[-17.94, 14.89, -92.07]}
            scale={0.01}
          />
          <instances.Achrome17
            position={[-19.94, -31.15, -99.03]}
            scale={0.01}
          />
          <instances.Achrome18 position={[3.27, -11.71, -97.56]} scale={0.01} />
          <instances.Agold position={[0.94, 32.79, 119.83]} scale={0.01} />
          <instances.Agold1 position={[0.94, -32.79, -119.83]} scale={0.01} />
          <instances.Aorange position={[-17.96, -31.15, 98.75]} scale={0.01} />
        </group>
        <group position={[-306.62, -183.32, 0.1]}>
          <instances.Chrome12 position={[-2.21, 24.74, -17.24]} scale={0.01} />
          <instances.Chrome13 position={[-2.21, 24.74, 17.24]} scale={0.01} />
          <instances.Gum13 position={[-0.49, -0.4, 67.54]} scale={0.01} />
          <instances.Gum14 position={[-0.49, -0.4, -67.54]} scale={0.01} />
          <instances.Silver2 position={[3.46, -23.91, 99.13]} scale={0.01} />
          <instances.Silver3 position={[3.46, -23.91, -99.13]} scale={0.01} />
        </group>
        <group position={[7.02, -151.14, 0.43]}>
          <instances.Achrome19 position={[79.45, -2.21, 96.97]} scale={0.01} />
          <instances.Agold2 position={[84.66, -2.21, -96.97]} scale={0.01} />
        </group>
        <group position={[-194.14, -159.29, -124.13]}>
          <instances.Achrome20
            position={[-12.59, -17.03, -42.34]}
            scale={0.01}
          />
          <instances.Achrome21 position={[41.51, -8.25, -11.47]} scale={0.01} />
          <instances.Aorange1
            position={[-12.59, -17.03, -41.01]}
            scale={0.01}
          />
        </group>
        <group position={[290.58, -155.52, -101.02]}>
          <instances.Chrome14 position={[0, 23.91, -1.51]} scale={0.01} />
          <instances.Chrome15 position={[0, 24.9, -19.49]} scale={0.01} />
          <instances.Gum15 position={[0.01, 0.05, -5.96]} scale={0.01} />
          <instances.Gum16 position={[0, 50.75, 1.49]} scale={0.01} />
        </group>
        <group position={[414.97, -155.52, -101.02]}>
          <instances.Chrome14 position={[0, 23.91, -1.51]} scale={0.01} />
          <instances.Gum15 position={[0.01, 0.05, -5.96]} scale={0.01} />
          <instances.Chrome16 position={[0, 24.9, -19.49]} scale={0.01} />
          <instances.Gum17 position={[0, 50.75, 1.49]} scale={0.01} />
        </group>
        <group position={[474.01, -153.63, 0.18]}>
          <instances.Chrome17 position={[-6.04, 37.65, -50.61]} scale={0.01} />
          <instances.Gum18 position={[-0.39, -0.58, 59.6]} scale={0.01} />
          <instances.Gum19 position={[-0.39, -0.58, -59.6]} scale={0.01} />
          <instances.Silver4 position={[8.48, -36.06, -100.3]} scale={0.01} />
          <instances.Silver5 position={[8.48, -36.06, 100.67]} scale={0.01} />
        </group>
        <group position={[-252.29, 18.8, 51.49]}>
          <instances.Achrome22 position={[6.61, -2.94, -139.56]} scale={0.01} />
          <instances.Agum2 position={[8.05, 24.09, -9.89]} scale={0.01} />
        </group>
        <group position={[-252.29, 18.8, -67.28]}>
          <instances.Achrome22 position={[6.61, -2.94, -139.56]} scale={0.01} />
          <instances.Agum2 position={[8.05, 24.09, -9.89]} scale={0.01} />
        </group>
        <group position={[-194.14, -159.29, 125.37]}>
          <instances.Achrome23
            position={[-12.59, -17.03, 42.35]}
            scale={0.01}
          />
          <group position={[41.51, -8.25, 11.47]} scale={0.01}>
            <instances.Mesh />
            <instances.Mesh1 />
          </group>
          <instances.Orange position={[-12.59, -17.03, 41.01]} scale={0.01} />
        </group>
        <instances.Ablackm position={[457.44, -138.49, 28.52]} scale={0.01} />
        <instances.Ablackm1 position={[304.42, -103.74, 23.03]} scale={0.01} />
        <instances.Achassis position={[71.43, -156, 42.29]} scale={0.01} />
        <instances.Achrome24
          position={[-218.05, 85.17, -125.14]}
          rotation={[0, 0, -0.09]}
          scale={0.01}
        />
        <instances.Achrome25 position={[-187.89, 114.14, 57.17]} scale={0.01} />
        <instances.Achrome26 position={[-195.65, 109.86, 71.42]} scale={0.01} />
        <group position={[227.42, -169.04, 100.54]} scale={0.01}>
          <instances.Mesh2 />
          <instances.Mesh3 />
        </group>
        <group position={[227.42, -169.04, -100.19]} scale={0.01}>
          <instances.Mesh4 />
          <instances.Mesh5 />
        </group>
        <instances.Achrome27 position={[120.96, -62.04, 145.46]} scale={0.01} />
        <group position={[-201.63, 45.15, 148.37]} scale={0.01}>
          <instances.Mesh6 />
          <instances.Mesh7 />
        </group>
        <instances.Achrome28
          position={[120.96, -62.04, -150.03]}
          scale={0.01}
        />
        <group position={[-201.63, 45.15, -148.37]} scale={0.01}>
          <instances.Mesh8 />
          <instances.Mesh9 />
        </group>
        <instances.Achrome29 position={[-43.6, -75.13, 31.17]} scale={0.01} />
        <instances.Achrome30 position={[-43.6, -75.13, -30.5]} scale={0.01} />
        <instances.Achrome31
          position={[-187.89, 114.14, -58.16]}
          scale={0.01}
        />
        <instances.Achrome32
          position={[-187.89, 123.13, -14.48]}
          scale={0.01}
        />
        <instances.Achrome33
          position={[-175.75, -16.64, -121.83]}
          scale={0.01}
        />
        <instances.Achrome34 position={[-186.13, 2.02, -126.72]} scale={0.01} />
        <instances.Achrome35
          position={[-175.75, -16.64, -121.83]}
          scale={0.01}
        />
        <instances.Achrome36 position={[36.36, 4.52, -121.83]} scale={0.01} />
        <instances.Achrome37 position={[33.96, 38.73, 140.71]} scale={0.01} />
        <instances.Achrome38 position={[33.96, 38.73, 140.71]} scale={0.01} />
        <instances.Achrome39
          position={[-175.75, -16.64, -121.83]}
          scale={0.01}
        />
        <group position={[777.66, -91.92, 137.02]} scale={0.01}>
          <instances.Mesh10 />
          <instances.Mesh11 />
        </group>
        <instances.Aglass position={[-175.75, -16.64, -121.83]} scale={0.01} />
        <instances.Agum3 position={[290.6, -155.39, -24.65]} scale={0.01} />
        <instances.Agum4 position={[415.07, -155.39, -24.65]} scale={0.01} />
        <instances.Agum5 position={[414.85, -159.27, 50.79]} scale={0.01} />
        <instances.Agum6 position={[-384.14, -155.54, -24.65]} scale={0.01} />
        <instances.Agum7 position={[-203.07, -169.99, 1.22]} scale={0.01} />
        <instances.Agum8 position={[-125.58, -169.4, 0.72]} scale={0.01} />
        <instances.Agum9 position={[-132.67, -170.43, 79.42]} scale={0.01} />
        <instances.Agum10 position={[-132.67, -170.43, -78.58]} scale={0.01} />
        <instances.Agum11 position={[-78.53, 18.54, -2.17]} scale={0.01} />
        <instances.AObject position={[-162.51, 77.26, -206.4]} scale={0.01} />
        <group position={[777.66, -91.92, 137.02]} scale={0.01}>
          <instances.Mesh12 />
          <instances.Mesh13 />
        </group>
        <group position={[777.66, -91.92, 137.02]} scale={0.01}>
          <instances.Mesh14 />
          <instances.Mesh15 />
        </group>
        <instances.Aredl position={[449.54, -138.49, 28.52]} scale={0.01} />
        <instances.Asilver2 position={[393.71, -118.6, 45.06]} scale={0.01} />
        <instances.Asilver3 position={[393.71, -118.6, -44.98]} scale={0.01} />
        <instances.Orange1 position={[-195.65, 109.86, -70.06]} scale={0.01} />
      </group>
      <instances.Text
        position={[0.47, 0.42, 0.6]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.04}
      />
      <instances.Text
        position={[-0.42, 0.41, 0.43]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={0.04}
      />
      <instances.Text
        position={[1.12, 0.25, -9.63]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.18}
      />
      <instances.Text
        position={[-1.07, 0.24, -10.5]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={0.18}
      />
      <group scale={0.01}>
        <instances.Solid />
        <instances.Solid1 />
        <instances.Solid2 />
        <instances.Solid3 />
        <instances.Solid4 />
        <instances.Solid5 />
        <instances.Solid6 />
        <instances.Solid7 />
        <instances.Solid8 />
        <instances.Solid9 />
        <instances.Solid10 />
        <instances.Solid11 />
        <instances.Solid12 />
        <instances.Solid13 />
        <instances.Solid14 />
        <instances.Solid15 />
        <instances.Solid16 />
        <instances.Solid17 />
        <instances.Solid18 />
        <instances.Solid19 />
        <instances.Solid20 />
        <instances.Solid21 />
        <instances.Solid22 />
        <instances.Solid23 />
        <instances.Solid24 />
        <instances.Solid25 />
        <instances.Solid26 />
        <instances.Solid27 />
        <instances.Solid28 />
        <instances.Solid29 />
        <instances.Solid30 />
        <instances.Solid31 />
        <instances.Solid32 />
        <instances.Solid33 />
        <instances.Solid34 />
        <instances.Solid35 />
        <instances.Solid36 />
        <instances.Solid37 />
        <instances.Solid38 />
        <instances.Solid39 />
        <instances.Solid40 />
        <instances.Solid41 />
        <instances.Solid42 />
        <instances.Solid43 />
        <instances.Solid44 />
        <instances.Solid45 />
        <instances.Solid46 />
        <instances.Solid47 />
        <instances.Solid48 />
        <instances.Solid49 />
        <instances.Solid50 />
        <instances.Solid51 />
        <instances.Solid52 />
        <instances.Solid53 />
      </group>
      <instances.Srf scale={0.01} />
      <instances.Srf1 scale={0.01} />
      <instances.Srf2 scale={0.01} />
      <instances.Srf3 scale={0.01} />
      <instances.Srf4 scale={0.01} />
      <instances.Srf5 scale={0.01} />
      <instances.Srf6 scale={0.01} />
      <instances.Srf7 scale={0.01} />
      <instances.Srf8 scale={0.01} />
      <instances.Text1
        position={[1.02, 1.55, -0.76]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.48}
      />
      <instances.Text1
        position={[-0.99, 1.57, -2.85]}
        rotation={[Math.PI / 2, 0, 1.57]}
        scale={0.45}
      />
      <instances.Text2
        position={[1.02, 1.58, -1.66]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.4}
      />
      <instances.Text2
        position={[-0.99, 1.59, -1.98]}
        rotation={[Math.PI / 2, 0, 1.57]}
        scale={0.4}
      />
    </group>
  );
}
