export const PUMPS_P = {
  "Pump 9": [
    {
      timestamp: 1.65833118e12,
      mnemonic: "Pump 9 Engine Load",
      value: "47",
      pump_position: "Pump 9",
      mnemonic_name: "Engine Load",
    },
    {
      timestamp: 1.65833118e12,
      mnemonic: "Pump 9 Horse Power",
      value: "595.9",
      pump_position: "Pump 9",
      mnemonic_name: "Horse Power",
    },
    {
      timestamp: 1.65833118e12,
      mnemonic: "Pump 9 Pump Rate",
      value: "4.1",
      pump_position: "Pump 9",
      mnemonic_name: "Pump Rate",
    },
    {
      timestamp: 1.65833118e12,
      mnemonic: "Pump 9 Trans Gear",
      value: "1",
      pump_position: "Pump 9",
      mnemonic_name: "Trans Gear",
    },
  ],
  "Pump 8": [
    {
      timestamp: 1.65833118e12,
      mnemonic: "Pump 8 Horse Power",
      value: "0",
      pump_position: "Pump 8",
      mnemonic_name: "Horse Power",
    },
    {
      timestamp: 1.65833118e12,
      mnemonic: "Pump 8 Pump Rate",
      value: "0",
      pump_position: "Pump 8",
      mnemonic_name: "Pump Rate",
    },
  ],
  "Pump 19": [
    {
      timestamp: 1.65833118e12,
      mnemonic: "Pump 19 Engine Load",
      value: "0",
      pump_position: "Pump 19",
      mnemonic_name: "Engine Load",
    },
    {
      timestamp: 1.65833118e12,
      mnemonic: "Pump 19 Horse Power",
      value: "0",
      pump_position: "Pump 19",
      mnemonic_name: "Horse Power",
    },
    {
      timestamp: 1.65833118e12,
      mnemonic: "Pump 19 Pump Rate",
      value: "0",
      pump_position: "Pump 19",
      mnemonic_name: "Pump Rate",
    },
    {
      timestamp: 1.65833118e12,
      mnemonic: "Pump 19 Trans Gear",
      value: "0",
      pump_position: "Pump 19",
      mnemonic_name: "Trans Gear",
    },
  ],
  "Pump 26": [
    {
      timestamp: 1.65833118e12,
      mnemonic: "Pump 26 Engine Load",
      value: "0",
      pump_position: "Pump 26",
      mnemonic_name: "Engine Load",
    },
    {
      timestamp: 1.65833118e12,
      mnemonic: "Pump 26 Horse Power",
      value: "0",
      pump_position: "Pump 26",
      mnemonic_name: "Horse Power",
    },
    {
      timestamp: 1.65833118e12,
      mnemonic: "Pump 26 Pump Rate",
      value: "0",
      pump_position: "Pump 26",
      mnemonic_name: "Pump Rate",
    },
    {
      timestamp: 1.65833118e12,
      mnemonic: "Pump 26 Trans Gear",
      value: "255",
      pump_position: "Pump 26",
      mnemonic_name: "Trans Gear",
    },
  ],
  "Pump 27": [
    {
      timestamp: 1.65833118e12,
      mnemonic: "Pump 27 Engine Load",
      value: "0",
      pump_position: "Pump 27",
      mnemonic_name: "Engine Load",
    },
    {
      timestamp: 1.65833118e12,
      mnemonic: "Pump 27 Horse Power",
      value: "0",
      pump_position: "Pump 27",
      mnemonic_name: "Horse Power",
    },
    {
      timestamp: 1.65833118e12,
      mnemonic: "Pump 27 Pump Rate",
      value: "0",
      pump_position: "Pump 27",
      mnemonic_name: "Pump Rate",
    },
    {
      timestamp: 1.65833118e12,
      mnemonic: "Pump 27 Trans Gear",
      value: "0",
      pump_position: "Pump 27",
      mnemonic_name: "Trans Gear",
    },
  ],
  "Pump 28": [
    {
      timestamp: 1.65833118e12,
      mnemonic: "Pump 28 Engine Load",
      value: "22",
      pump_position: "Pump 28",
      mnemonic_name: "Engine Load",
    },
    {
      timestamp: 1.65833118e12,
      mnemonic: "Pump 28 Horse Power",
      value: "0",
      pump_position: "Pump 28",
      mnemonic_name: "Horse Power",
    },
    {
      timestamp: 1.65833118e12,
      mnemonic: "Pump 28 Pump Rate",
      value: "0",
      pump_position: "Pump 28",
      mnemonic_name: "Pump Rate",
    },
    {
      timestamp: 1.65833118e12,
      mnemonic: "Pump 28 Trans Gear",
      value: "254",
      pump_position: "Pump 28",
      mnemonic_name: "Trans Gear",
    },
  ],
  "Pump 29": [
    {
      timestamp: 1.65833118e12,
      mnemonic: "Pump 29 Engine Load",
      value: "12",
      pump_position: "Pump 29",
      mnemonic_name: "Engine Load",
    },
    {
      timestamp: 1.65833118e12,
      mnemonic: "Pump 29 Horse Power",
      value: "0",
      pump_position: "Pump 29",
      mnemonic_name: "Horse Power",
    },
    {
      timestamp: 1.65833118e12,
      mnemonic: "Pump 29 Pump Rate",
      value: "0",
      pump_position: "Pump 29",
      mnemonic_name: "Pump Rate",
    },
    {
      timestamp: 1.65833118e12,
      mnemonic: "Pump 29 Trans Gear",
      value: "254",
      pump_position: "Pump 29",
      mnemonic_name: "Trans Gear",
    },
  ],
  "Pump 22": [
    {
      timestamp: 1.65833118e12,
      mnemonic: "Pump 22 Engine Load",
      value: "1",
      pump_position: "Pump 22",
      mnemonic_name: "Engine Load",
    },
    {
      timestamp: 1.65833118e12,
      mnemonic: "Pump 22 Trans Gear",
      value: "1",
      pump_position: "Pump 22",
      mnemonic_name: "Trans Gear",
    },
  ],
  "Pump 23": [
    {
      timestamp: 1.65833118e12,
      mnemonic: "Pump 23 Engine Load",
      value: "1",
      pump_position: "Pump 23",
      mnemonic_name: "Engine Load",
    },
    {
      timestamp: 1.65833118e12,
      mnemonic: "Pump 23 Trans Gear",
      value: "1",
      pump_position: "Pump 23",
      mnemonic_name: "Trans Gear",
    },
  ],
  "Pump 24": [
    {
      timestamp: 1.65833118e12,
      mnemonic: "Pump 24 Engine Load",
      value: "1",
      pump_position: "Pump 24",
      mnemonic_name: "Engine Load",
    },
    {
      timestamp: 1.65833118e12,
      mnemonic: "Pump 24 Trans Gear",
      value: "1",
      pump_position: "Pump 24",
      mnemonic_name: "Trans Gear",
    },
  ],
  "Pump 25": [
    {
      timestamp: 1.65833118e12,
      mnemonic: "Pump 25 Engine Load",
      value: "0",
      pump_position: "Pump 25",
      mnemonic_name: "Engine Load",
    },
    {
      timestamp: 1.65833118e12,
      mnemonic: "Pump 25 Horse Power",
      value: "0",
      pump_position: "Pump 25",
      mnemonic_name: "Horse Power",
    },
    {
      timestamp: 1.65833118e12,
      mnemonic: "Pump 25 Pump Rate",
      value: "0",
      pump_position: "Pump 25",
      mnemonic_name: "Pump Rate",
    },
    {
      timestamp: 1.65833118e12,
      mnemonic: "Pump 25 Trans Gear",
      value: "255",
      pump_position: "Pump 25",
      mnemonic_name: "Trans Gear",
    },
  ],
  "Pump 41": [
    {
      timestamp: 1.65833118e12,
      mnemonic: "Pump 41 Horse Power",
      value: "0",
      pump_position: "Pump 41",
      mnemonic_name: "Horse Power",
    },
  ],
  "Pump 20": [
    {
      timestamp: 1.65833118e12,
      mnemonic: "Pump 20 Engine Load",
      value: "1",
      pump_position: "Pump 20",
      mnemonic_name: "Engine Load",
    },
    {
      timestamp: 1.65833118e12,
      mnemonic: "Pump 20 Trans Gear",
      value: "1",
      pump_position: "Pump 20",
      mnemonic_name: "Trans Gear",
    },
  ],
  "Pump 21": [
    {
      timestamp: 1.65833118e12,
      mnemonic: "Pump 21 Engine Load",
      value: "1",
      pump_position: "Pump 21",
      mnemonic_name: "Engine Load",
    },
    {
      timestamp: 1.65833118e12,
      mnemonic: "Pump 21 Trans Gear",
      value: "1",
      pump_position: "Pump 21",
      mnemonic_name: "Trans Gear",
    },
  ],
  "Pump 15": [
    {
      timestamp: 1.65833118e12,
      mnemonic: "Pump 15 Engine Load",
      value: "43",
      pump_position: "Pump 15",
      mnemonic_name: "Engine Load",
    },
    {
      timestamp: 1.65833118e12,
      mnemonic: "Pump 15 Horse Power",
      value: "719",
      pump_position: "Pump 15",
      mnemonic_name: "Horse Power",
    },
    {
      timestamp: 1.65833118e12,
      mnemonic: "Pump 15 Pump Rate",
      value: "4.9",
      pump_position: "Pump 15",
      mnemonic_name: "Pump Rate",
    },
    {
      timestamp: 1.65833118e12,
      mnemonic: "Pump 15 Trans Gear",
      value: "1",
      pump_position: "Pump 15",
      mnemonic_name: "Trans Gear",
    },
  ],
  "Pump 16": [
    {
      timestamp: 1.65833118e12,
      mnemonic: "Pump 16 Engine Load",
      value: "37",
      pump_position: "Pump 16",
      mnemonic_name: "Engine Load",
    },
    {
      timestamp: 1.65833118e12,
      mnemonic: "Pump 16 Horse Power",
      value: "440.3",
      pump_position: "Pump 16",
      mnemonic_name: "Horse Power",
    },
    {
      timestamp: 1.65833118e12,
      mnemonic: "Pump 16 Pump Rate",
      value: "2.9",
      pump_position: "Pump 16",
      mnemonic_name: "Pump Rate",
    },
    {
      timestamp: 1.65833118e12,
      mnemonic: "Pump 16 Trans Gear",
      value: "1",
      pump_position: "Pump 16",
      mnemonic_name: "Trans Gear",
    },
  ],
  "Pump 17": [
    {
      timestamp: 1.65833118e12,
      mnemonic: "Pump 17 Horse Power",
      value: "0",
      pump_position: "Pump 17",
      mnemonic_name: "Horse Power",
    },
    {
      timestamp: 1.65833118e12,
      mnemonic: "Pump 17 Pump Rate",
      value: "0",
      pump_position: "Pump 17",
      mnemonic_name: "Pump Rate",
    },
  ],
  "Pump 39": [
    {
      timestamp: 1.65833118e12,
      mnemonic: "Pump 39 Pump Rate",
      value: "0",
      pump_position: "Pump 39",
      mnemonic_name: "Pump Rate",
    },
  ],
  "Pump 18": [
    {
      timestamp: 1.65833118e12,
      mnemonic: "Pump 18 Horse Power",
      value: "0",
      pump_position: "Pump 18",
      mnemonic_name: "Horse Power",
    },
    {
      timestamp: 1.65833118e12,
      mnemonic: "Pump 18 Pump Rate",
      value: "0",
      pump_position: "Pump 18",
      mnemonic_name: "Pump Rate",
    },
  ],
  "Pump 13": [
    {
      timestamp: 1.65833118e12,
      mnemonic: "Pump 13 Engine Load",
      value: "0",
      pump_position: "Pump 13",
      mnemonic_name: "Engine Load",
    },
    {
      timestamp: 1.65833118e12,
      mnemonic: "Pump 13 Horse Power",
      value: "0",
      pump_position: "Pump 13",
      mnemonic_name: "Horse Power",
    },
    {
      timestamp: 1.65833118e12,
      mnemonic: "Pump 13 Pump Rate",
      value: "0",
      pump_position: "Pump 13",
      mnemonic_name: "Pump Rate",
    },
    {
      timestamp: 1.65833118e12,
      mnemonic: "Pump 13 Trans Gear",
      value: "-1",
      pump_position: "Pump 13",
      mnemonic_name: "Trans Gear",
    },
  ],
  "Pump 14": [
    {
      timestamp: 1.65833118e12,
      mnemonic: "Pump 14 Engine Load",
      value: "37",
      pump_position: "Pump 14",
      mnemonic_name: "Engine Load",
    },
    {
      timestamp: 1.65833118e12,
      mnemonic: "Pump 14 Horse Power",
      value: "389.4",
      pump_position: "Pump 14",
      mnemonic_name: "Horse Power",
    },
    {
      timestamp: 1.65833118e12,
      mnemonic: "Pump 14 Pump Rate",
      value: "2.6",
      pump_position: "Pump 14",
      mnemonic_name: "Pump Rate",
    },
    {
      timestamp: 1.65833118e12,
      mnemonic: "Pump 14 Trans Gear",
      value: "1",
      pump_position: "Pump 14",
      mnemonic_name: "Trans Gear",
    },
  ],
  "Pump 30": [
    {
      timestamp: 1.65833118e12,
      mnemonic: "Pump 30 Engine Load",
      value: "16",
      pump_position: "Pump 30",
      mnemonic_name: "Engine Load",
    },
    {
      timestamp: 1.65833118e12,
      mnemonic: "Pump 30 Horse Power",
      value: "0",
      pump_position: "Pump 30",
      mnemonic_name: "Horse Power",
    },
    {
      timestamp: 1.65833118e12,
      mnemonic: "Pump 30 Pump Rate",
      value: "0",
      pump_position: "Pump 30",
      mnemonic_name: "Pump Rate",
    },
    {
      timestamp: 1.65833118e12,
      mnemonic: "Pump 30 Trans Gear",
      value: "254",
      pump_position: "Pump 30",
      mnemonic_name: "Trans Gear",
    },
  ],
  "Pump 6": [
    {
      timestamp: 1.65833118e12,
      mnemonic: "Pump 6 Engine Load",
      value: "34",
      pump_position: "Pump 6",
      mnemonic_name: "Engine Load",
    },
    {
      timestamp: 1.65833118e12,
      mnemonic: "Pump 6 Horse Power",
      value: "427.3",
      pump_position: "Pump 6",
      mnemonic_name: "Horse Power",
    },
    {
      timestamp: 1.65833118e12,
      mnemonic: "Pump 6 Pump Rate",
      value: "2.9",
      pump_position: "Pump 6",
      mnemonic_name: "Pump Rate",
    },
    {
      timestamp: 1.65833118e12,
      mnemonic: "Pump 6 Trans Gear",
      value: "1",
      pump_position: "Pump 6",
      mnemonic_name: "Trans Gear",
    },
  ],
  "Pump 31": [
    {
      timestamp: 1.65833118e12,
      mnemonic: "Pump 31 Engine Load",
      value: "14",
      pump_position: "Pump 31",
      mnemonic_name: "Engine Load",
    },
    {
      timestamp: 1.65833118e12,
      mnemonic: "Pump 31 Horse Power",
      value: "0",
      pump_position: "Pump 31",
      mnemonic_name: "Horse Power",
    },
    {
      timestamp: 1.65833118e12,
      mnemonic: "Pump 31 Pump Rate",
      value: "0",
      pump_position: "Pump 31",
      mnemonic_name: "Pump Rate",
    },
    {
      timestamp: 1.65833118e12,
      mnemonic: "Pump 31 Trans Gear",
      value: "254",
      pump_position: "Pump 31",
      mnemonic_name: "Trans Gear",
    },
  ],
  "Pump 5": [
    {
      timestamp: 1.65833118e12,
      mnemonic: "Pump 5 Engine Load",
      value: "37",
      pump_position: "Pump 5",
      mnemonic_name: "Engine Load",
    },
    {
      timestamp: 1.65833118e12,
      mnemonic: "Pump 5 Horse Power",
      value: "389.3",
      pump_position: "Pump 5",
      mnemonic_name: "Horse Power",
    },
    {
      timestamp: 1.65833118e12,
      mnemonic: "Pump 5 Pump Rate",
      value: "2.6",
      pump_position: "Pump 5",
      mnemonic_name: "Pump Rate",
    },
    {
      timestamp: 1.65833118e12,
      mnemonic: "Pump 5 Trans Gear",
      value: "1",
      pump_position: "Pump 5",
      mnemonic_name: "Trans Gear",
    },
  ],
  "Pump 32": [
    {
      timestamp: 1.65833118e12,
      mnemonic: "Pump 32 Engine Load",
      value: "20",
      pump_position: "Pump 32",
      mnemonic_name: "Engine Load",
    },
    {
      timestamp: 1.65833118e12,
      mnemonic: "Pump 32 Horse Power",
      value: "0",
      pump_position: "Pump 32",
      mnemonic_name: "Horse Power",
    },
    {
      timestamp: 1.65833118e12,
      mnemonic: "Pump 32 Pump Rate",
      value: "0",
      pump_position: "Pump 32",
      mnemonic_name: "Pump Rate",
    },
    {
      timestamp: 1.65833118e12,
      mnemonic: "Pump 32 Trans Gear",
      value: "254",
      pump_position: "Pump 32",
      mnemonic_name: "Trans Gear",
    },
  ],
  "Pump 4": [
    {
      timestamp: 1.65833118e12,
      mnemonic: "Pump 4 Engine Load",
      value: "38",
      pump_position: "Pump 4",
      mnemonic_name: "Engine Load",
    },
    {
      timestamp: 1.65833118e12,
      mnemonic: "Pump 4 Horse Power",
      value: "431.9",
      pump_position: "Pump 4",
      mnemonic_name: "Horse Power",
    },
    {
      timestamp: 1.65833118e12,
      mnemonic: "Pump 4 Pump Rate",
      value: "2.9",
      pump_position: "Pump 4",
      mnemonic_name: "Pump Rate",
    },
    {
      timestamp: 1.65833118e12,
      mnemonic: "Pump 4 Trans Gear",
      value: "1",
      pump_position: "Pump 4",
      mnemonic_name: "Trans Gear",
    },
  ],
  "Pump 2": [
    {
      timestamp: 1.65833118e12,
      mnemonic: "Pump 2 Engine Load",
      value: "43",
      pump_position: "Pump 2",
      mnemonic_name: "Engine Load",
    },
    {
      timestamp: 1.65833118e12,
      mnemonic: "Pump 2 Horse Power",
      value: "706.8",
      pump_position: "Pump 2",
      mnemonic_name: "Horse Power",
    },
    {
      timestamp: 1.65833118e12,
      mnemonic: "Pump 2 Pump Rate",
      value: "4.8",
      pump_position: "Pump 2",
      mnemonic_name: "Pump Rate",
    },
    {
      timestamp: 1.65833118e12,
      mnemonic: "Pump 2 Trans Gear",
      value: "1",
      pump_position: "Pump 2",
      mnemonic_name: "Trans Gear",
    },
  ],
  "Pump 1": [
    {
      timestamp: 1.65833118e12,
      mnemonic: "Pump 1 Engine Load",
      value: "47",
      pump_position: "Pump 1",
      mnemonic_name: "Engine Load",
    },
    {
      timestamp: 1.65833118e12,
      mnemonic: "Pump 1 Horse Power",
      value: "575.1",
      pump_position: "Pump 1",
      mnemonic_name: "Horse Power",
    },
    {
      timestamp: 1.65833118e12,
      mnemonic: "Pump 1 Pump Rate",
      value: "3.9",
      pump_position: "Pump 1",
      mnemonic_name: "Pump Rate",
    },
    {
      timestamp: 1.65833118e12,
      mnemonic: "Pump 1 Trans Gear",
      value: "1",
      pump_position: "Pump 1",
      mnemonic_name: "Trans Gear",
    },
  ],
};
